# Generated by Django 4.0 on 2021-12-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_bus_options_alter_goes_to_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
